class ResponseMessage:
    INVALID_DATA = "Invalid data provided."
    EMAIL_ALREADY_EXIST = "Trainer with this email already exists."
    EMAIL_NOT_FOUND = "Email not found in external service."
    SERVICE_UNAVAILABLE = "External service unavailable, please provide name manually."
    SOMETHING_WRONG = "Something went wrong, please provide name manually."
    TRAINER_CREATED = "Trainer created successfully."
    TRAINER_NOT_FOUND = "Trainer not found."
    MODULE_CREATED = "Module created successfully."
    MODULE_NOT_FOUND = "Module with provided id not found."
    INVALID_EXT = "Only PDF and DOCX files are allowed."
    INVALID_FILE_SIZE = "File size exceeds 2MB."
    RESOURCE_CREATED = "Resource uploaded successfully."
    INVALID_MODULE = "All modules must belong to the same trainer."
